# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'TBKmini XIAO BLE build'
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["xiao_ble"]'
      shield: '["xiao_ble_left","xiao_ble_right"]'
      alphas: '["ColemakDHK"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
