# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build XIAO'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["xiao_ble"]'
      shield: '["corne_left","corne_right"]'
      alphas: '["ColemakDHK"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      custom_config: '["#define MIRYOKU_KLUDGE_TAPDELAY"]'
